server:
  port: 8080
  servlet:
    context-path: /shop
spring:
  thymeleaf:
    check-template-location: true
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML5
    suffix: .html
    prefix: classpath:/templates/
  application:
    name: frontend

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

